# Generated by Django 3.2.6 on 2024-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castomization',
            name='file',
            field=models.ImageField(blank=True, upload_to='post-images'),
        ),
    ]
