# Generated by Django 3.2.6 on 2024-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_castomization_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castomization',
            name='content',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
