# Generated by Django 3.2.6 on 2024-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_castomization_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castomization',
            name='file',
            field=models.ImageField(blank=True, upload_to='site-illustrations'),
        ),
    ]
