# Generated by Django 3.2.6 on 2024-02-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_castomization_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Castomization',
            new_name='Customization',
        ),
    ]
