# Generated by Django 3.2.6 on 2024-03-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_castomization_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='content',
            field=models.CharField(blank=True, max_length=210),
        ),
    ]
