# Generated by Django 3.2.6 on 2024-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customization_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('text', models.CharField(blank=True, max_length=15000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(upload_to='article-images')),
                ('tags', models.ManyToManyField(blank='True', to='api.Tag')),
            ],
        ),
    ]
