# Generated by Django 3.2.6 on 2024-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='article-images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
