# Generated by Django 3.2.6 on 2024-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(max_length=255, upload_to='post-images'),
        ),
    ]
