# Generated by Django 4.2.9 on 2024-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('last_post_id', models.IntegerField(blank=True)),
                ('last_article_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
