# Generated by Django 4.2.9 on 2024-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='content',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
