# Generated by Django 4.2.9 on 2024-08-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customization_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.ImageField(upload_to='smiles/')),
            ],
        ),
    ]
