# Generated by Django 4.2.9 on 2024-08-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_smile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smile',
            name='name',
        ),
    ]
